In [3]:
import torch

In [2]:
import torch

In [3]:
print(torch.__version__)

1.3.1


In [4]:
torch.cuda.is_available()

False

In [5]:
d = [[1,2,3],[4,5,6],[7,8,9]]
d


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
t = torch.tensor(d)

In [7]:
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

# Basic Tensor functions

In [8]:
type(t)

torch.Tensor

In [9]:
t.shape

torch.Size([3, 3])

In [79]:
t.size()

torch.Size([3, 3])

In [12]:
t.reshape(1,9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [13]:
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [14]:
t1 =t.reshape(1,9)

In [15]:
t1

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [16]:
t1.shape

torch.Size([1, 9])

In [78]:
t1.size()

torch.Size([3])

In [17]:
t.dtype


torch.int64

In [18]:
t.device

device(type='cpu')

In [19]:
t.layout

torch.strided

In [82]:
#rank of a tensor = length of shape of a tensor 
len(t.shape)

2

In [83]:
#No of elements within a tensor without inbuilt function

torch.tensor(t.shape).prod()

tensor(9)

In [84]:
#No of elements within a tensor with inbuilt function
t.numel()

9

# Creating Tesors with data 

In [73]:
import torch
import numpy as np
data = np.array([1,2,3])

In [ ]:
#now data is in numpy array lets create tensors using these arrays 
#METHOD 1 
torch.Tensor(data)#this will create a tensor object therefore the data inside the tensor is float

In [23]:
#METHOD 2
torch.tensor(data)

tensor([1, 2, 3])

In [26]:
#METHOD 3 
torch.as_tensor(data)

tensor([1, 2, 3])

In [27]:
#METHOD 4 
torch.from_numpy(data)

tensor([1, 2, 3])

# Creating tensors without data

In [28]:
# torch.eye(n) this create a identity matrix ie 1 at diagonals and rest 0 . n = no of rows to be formed
print(torch.eye(3))

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [35]:
#METHOD 2  torch.zeros([n,m]) this gives a n*n matrix with all elements zeros
print(torch.zeros([2,2]))
print(torch.zeros(2,2))

tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.]])


In [33]:
#METHOD 3 torch.ones(n,m) n*m matrix with all elements 1 
print(torch.ones([3,3]))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [36]:
#METHOD 4  torch.rand(n,m)  --- generate a n * m matrix with random floating numbers
print(torch.rand(3,3))

tensor([[0.2804, 0.2784, 0.5043],
        [0.6463, 0.5824, 0.8481],
        [0.1785, 0.0321, 0.0110]])


# basic Tensor operations 


In [42]:
t1 = torch.Tensor(data)
t1.dtype

torch.float32

In [43]:
t2 = torch.tensor(data)
t2.dtype

torch.int64

In [39]:
# t1 and t2 are of different data type one being float and one being int 
t1 + t2 
# altough it works but we should not do this ...we must try to perform operations on similar data type 

tensor([2., 4., 6.])

In [44]:
t1 * t2 

tensor([1., 4., 9.])

In [46]:
t1/ t2 

tensor([1., 1., 1.])

In [47]:
t1 - t2 

tensor([0., 0., 0.])

# Best option for creating tensors using data

In [48]:
# torch.Tensor(data) is a constructor which gives us the default data type while rest are factory functions
#in factory function the tensor has same dtype as input . we can even specify the data type 
torch.get_default_dtype()

torch.float32

In [68]:
torch.tensor(data, dtype=torch.float32)


tensor([1., 0., 3.])

In [69]:
torch.as_tensor(data, dtype=torch.float32)


tensor([1., 0., 3.])

In [59]:
#EXCEPT 
torch.from_numpy(data,dtype =torch.float32)

TypeError: from_numpy() takes no keyword arguments

* THIS CLEARLY STATES THAT torch.tensor() and torch.as_tensor() are better than the rest two 

#### Shared Memory vs Copying 

In [74]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 =torch.from_numpy(data)


In [75]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [76]:
data[1] = 0

In [77]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 0, 3])
tensor([1, 0, 3])


WHY LAST 2 CHANGED ?? Because they share memory with the numpy array i.e data  , while rest creates a copy

## SUMMARY 

WHY LAST 2 CHANGED ?? Because they share memory with the numpy array i.e data  , while rest creates a copy

NOW WHICH ONE IS THE BEST ? torch.as_tensors or torch.tensor()

The torch.tensor() call is the sort of go-to call,
while torch.as_tensor() should be employed when tuning our code for performance.

# RESHAPING OPERATIONS
It is one of the most important tensor operation.

In [12]:
d = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]

In [13]:
t = torch.tensor(d)
print(t)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])


In [14]:
t.reshape([1,12])

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [15]:
t.reshape(3,4)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [16]:
t.reshape([4,3])

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [17]:
t.reshape([6,2])

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]])

In [18]:
t.reshape([2,6])

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

In [19]:
t.reshape(1,12)

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [20]:
t.reshape(5,2)

RuntimeError: shape '[5, 2]' is invalid for input of size 12

### ROW * COLUMN = 12 (in this case as total number of elements are  12)

In [21]:
t.numel()

12

In [22]:
len(t.shape)

2

### we can even make tensors whoes rank are greater than 2  only condition is that  product of all dimensions shoould be equal to no of elements (here 12)

In [25]:
tn = t.reshape(2,2,3)
tn

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [27]:
len(tn.shape)
#rank of tn  which was previously 2 

3

# Changing shape by squeezing and unsqueezing
### Squeezing a tensor removes the dimensions or axes that have a length of one.
### Unsqueezing a tensor adds a dimension with a length of one. and this takes the dimension as parameter
#### These functions allow us to expand or shrink the rank (number of dimensions) of our tensor.

In [34]:
t.squeeze()

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [81]:
ts = t.reshape([1,12]).squeeze()
ts

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [38]:
tp = t.reshape(1,12)
tp.shape

torch.Size([1, 12])

In [36]:
ts.shape

torch.Size([12])

In [42]:
ts.unsqueeze(dim=0).shape

torch.Size([1, 12])

In [48]:
tp.unsqueeze(dim=0).shape

torch.Size([1, 1, 12])

In [49]:
tp.unsqueeze(dim= 2).shape

torch.Size([1, 12, 1])

 ## Flatten a tensor 
#### Flattening a tensor means to remove all of the dimensions except for one.
##### flatten operations are required when passing an output tensor from a convolutional layer to a linear layer

In [64]:
tf = t.reshape(1,12)
tf 

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [65]:
tf.shape
#it still is 2 dimensional 

torch.Size([1, 12])

In [66]:
tf = tf.squeeze()
tf

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [67]:
tf.shape
#this is now  1 dimensional

torch.Size([12])

In [56]:
#lets make a function for this which accept a tensor and then return a flatten tensor 
#the -1 tells the reshape() function to figure out what the value should be based on the number of elements contained 
#within the tensor. Remember, the shape must equal the product of the shape's component values. 
#This is how PyTorch can figure out what the value should be, given a 1 as the first argument.
def flatten(t):
    t = t.reshape(1, -1)
    t = t.squeeze()
    return t

In [69]:
tff = flatten(t)
tff

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [70]:
tff.shape

torch.Size([12])

# Concatenating tensors
### We combine tensors using the cat() function, and the resulting tensor will have a shape that depends on the shape of the two input tensors.

In [73]:
t1 = torch.tensor([
    [1,2],
    [3,4]])


In [74]:
t2 = torch.tensor([
    [5,6],
    [7,8]
])

In [75]:
t1

tensor([[1, 2],
        [3, 4]])

In [76]:
t2

tensor([[5, 6],
        [7, 8]])

In [77]:
torch.cat((t1, t2), dim=0)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [78]:
torch.cat((t1, t2), dim=1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

In [79]:
torch.cat((t1, t2), dim=0).shape

torch.Size([4, 2])

In [80]:
torch.cat((t1, t2), dim=1).shape

torch.Size([2, 4])