# Reduction operations and Access operations



## Tensor reduction operations

#### A reduction operation on a tensor is an operation that reduces the number of elements contained within the tensor.

tensors are the data structures of deep learning. Our first task is to load our data elements into a tensor and manage 
that data

Reshaping operations gave us the ability to position our elements along particular axes.
Element-wise operations allow us to perform operations on elements between two tensors,
and reduction operations allow us to perform operations on elements within a single tensor.

In [8]:
import torch
import numpy as np 
t = torch.tensor([
    [0,1,0],
    [2,0,2],
    [0,3,0]
],dtype = torch.float32)

In [9]:
t

tensor([[0., 1., 0.],
        [2., 0., 2.],
        [0., 3., 0.]])

our first reduction operation, a summation. Then we will look at mean , product and standard deviation 

In [10]:
t.sum()

tensor(8.)

In [11]:
t.sum().tolist()

8.0

In [12]:
t.prod()

tensor(0.)

In [13]:
t.mean()
#Can only calculate the mean of floating types

tensor(0.8889)

In [14]:
t.std()

tensor(1.1667)

### Reducing tensors by axes

In [17]:
t1 = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)

In [19]:
print(t1.shape)
print(len(t1.shape))
#shape and rank

torch.Size([3, 4])
2


In [20]:
t1.sum()

tensor(24.)

In [30]:
t1.sum(dim =0)
# we are reducing this tensor across the first axis, and elements running along the first axis are arrays,
#and the elements running along the second axis are numbers.

tensor([6., 6., 6., 6.])

In [24]:
t1.sum(dim =1 )

tensor([ 4.,  8., 12.])

In [25]:
t1[0]

tensor([1., 1., 1., 1.])

In [31]:
t1[1]

tensor([2., 2., 2., 2.])

In [32]:
t1[2]

tensor([3., 3., 3., 3.])

In [33]:
t1[0] + t1[1] + t1[2]
#which is same as t1.sum(dim =0)

tensor([6., 6., 6., 6.])

In [35]:
 t1[0].sum()

tensor(4.)

In [36]:
 t1[1].sum()

tensor(8.)

In [37]:
 t1[2].sum()

tensor(12.)

In [38]:
t1.sum(dim =1 )

tensor([ 4.,  8., 12.])

###  Let’s look now a very common reduction operation used in neural network programming called Argmax.

## Argmax returns the index location of the maximum value inside a tensor.

###### When we call the argmax() method on a tensor, the tensor is reduced to a new tensor that contains an index value indicating where the max value is inside the tensor.

In [39]:
t2 = torch.tensor([
    [1,0,0,2],
    [0,3,3,0],
    [4,0,0,5]
], dtype=torch.float32)

In [40]:
t2.max()
#this gives the max value in the tensor 

tensor(5.)

In [41]:
t2.argmax()
#What is 11 here ???11 is the index of the max value . But how we know that the index is 11.Lets see by flatting tensor

tensor(11)

In [45]:
t2.flatten().tolist().index(5)
#now we have a idea why argmax gives 11 .

11

#### Let's see how we can work with specific axes now.

In [48]:
t2.max(dim=0)
# we can find max of a tensor like this but we can not change this to a list or a numpy array for further computation

torch.return_types.max(
values=tensor([4., 3., 3., 5.]),
indices=tensor([2, 1, 1, 2]))

In [50]:
t2.argmax(dim=0)
#this will give the indices of the max value along dimension 0 

tensor([2, 1, 1, 2])

In [51]:
t2.argmax(dim = 0 ).tolist()

[2, 1, 1, 2]

In [52]:
t2.argmax(dim =0 ).numpy()
#we can change indices to a list or even a numpy array

array([2, 1, 1, 2])

In [53]:
t2.argmax(dim =1 )

tensor([3, 2, 3])

#### In practice, we often use the argmax() function on a network’s output prediction tensor, to determine which category has the highest prediction value.

## Accessing elements inside tensors

When multiple values are returned, and we can access the numeric values by transforming the output tensor into a Python list or a NumPy array.

In [54]:
t3 = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
], dtype=torch.float32)


In [55]:
t3.mean()
#what if we want to have the value 

tensor(5.)

In [57]:
t3.mean().item()

5.0