### How Linear Layers Work
linear layers use matrix multiplication to transform their in features to out features.

When the input features are received by a linear layer, they are received in the form of a flattened 1-dimensional tensor and are then multiplied by the weight matrix. This matrix multiplication produces the output features.

In [3]:
import torch 
import torch.nn as nn


In [4]:
in_features = torch.tensor([1,2,3,4], dtype=torch.float32)

In [5]:
weight_matrix = torch.tensor([
    [1,2,3,4],
    [2,3,4,5],
    [3,4,5,6]
], dtype=torch.float32)

In [6]:
weight_matrix.matmul(in_features)

tensor([30., 40., 50.])

This is how linear layers work as well. They map an in_feature space to an out_feature space using a weight matrix.

Let's see how to create a PyTorch linear layer that will do this same operation.

In [7]:
fc = nn.Linear(in_features=4, out_features=3)

In [8]:
fc(in_features)
# here we can see when we pass 4 in features it indeed gives us 3 out features as we mentioned .HOW?
#PyTorch is using these value to create a matrix of size out_features * in_features i.e. 3*4 
#And then multiply the 3 *4 weight matrix with 4 *1 flat input tensor to give 3 *1 output tensor

tensor([-0.6724, -1.7043,  2.8615], grad_fn=<AddBackward0>)

#### We can call the object instance like this because PyTorch neural network modules are callable Python objects. 
Different values were produced.

This is because PyTorch creates a weight matrix and initializes it with random values

Let's explicitly set the weight matrix of the linear layer to be the same as the one we used in our other example.

In [9]:
fc.weight = nn.Parameter(weight_matrix)  

In [10]:
fc(in_features)

tensor([30.4009, 39.6187, 49.5835], grad_fn=<AddBackward0>)

Stil we got values which are not exactly the same as start . WHY?

Because Bias is True as a default and bias is added to the product of those two .

lets set bias = false 

In [11]:
fc = nn.Linear(in_features=4, out_features=3, bias=False)
fc.weight = nn.Parameter(weight_matrix)

In [12]:
fc(in_features)
#Now we got the exact value . This is how linear layers work.

tensor([30., 40., 50.], grad_fn=<SqueezeBackward3>)

## Callable Layers and Neural Networks