## Concatenating joins a sequence of tensors along an existing axis, and stacking joins a sequence of tensors along a new axis.

In [1]:
import torch
t1 = torch.tensor([1,1,1])

In [2]:
t1.unsqueeze(dim=0)

tensor([[1, 1, 1]])

In [3]:
t1.unsqueeze(dim=1)

tensor([[1],
        [1],
        [1]])

## Stack vs Cat in PyTorch

In [4]:
import torch

t1 = torch.tensor([1,1,1])
t2 = torch.tensor([2,2,2])
t3 = torch.tensor([3,3,3])

In [5]:
torch.cat(
    (t1,t2,t3)
    ,dim=0
)

tensor([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [6]:
torch.cat((t1,t2,t3))

tensor([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [7]:
 torch.stack(
    (t1,t2,t3)
    ,dim=0
)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [8]:
 torch.stack(
    (t1,t2,t3)
   
)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [13]:
 torch.stack(
    (t1,t2,t3)
    ,dim=1
)

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [11]:
#Lets see how  does stack work in the background
torch.cat(
    (
         t1.unsqueeze(0)
        ,t2.unsqueeze(0)
        ,t3.unsqueeze(0)
    )
    ,dim=0
)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [14]:
 torch.cat(
    (
         t1.unsqueeze(1)
        ,t2.unsqueeze(1)
        ,t3.unsqueeze(1)
    )
    ,dim=1
)

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])